name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: macos-latest
    env:
      XC_VERSION: ${{ '12.4' }}
      XC_WORKSPACE: ${{ 'TideApp/TideApp.xcworkspace' }}
      XC_SCHEME: ${{ 'TideApp' }}
    steps:
    - name: Run CIScript
      run: ([ -e TideApp/CIScript.sh ] && sh TideApp/CIScript.sh) || echo 'WARNING - CIScript.sh file not found'
    - name: Use Xcode "$XC_VERSION"
      run: sudo xcode-select -switch /Applications/Xcode_$XC_VERSION.app
    - uses: actions/checkout@v2
    - name: Run Unit and UI Tests
      run: /usr/bin/xcodebuild test -workspace "$XC_WORKSPACE" -scheme "$XC_SCHEME" -destination 'platform=iOS Simulator,name=iPhone 11'
